
services:
  consul:
    image: "hashicorp/consul:latest"

    ports:
      - "8500:8500"
  mysql:
    image: 'mysql:latest'
    ports:
      - 3308:3306
    # network_mode: "host" # <-- networkMode
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD=123456789
    volumes:
      - ./db/sql/ini:/docker-entrypoint-initdb.d
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379